### ISSUE TITLE
Error while initializing the honeyscanner

### ISSUE THREAD

**Issue by ankitkat042** [honeynet/honeyscanner#31]
Hey @m-vasiloma and @aristofanischionis,

I'm working on setting up the project for GSoC '24 since I really liked the idea of this project.
I managed to fix a networking problem on my VM by myself. 
![image](https://github.com/honeynet/honeyscanner/assets/79627254/ba5f49c9-be9f-4e98-842e-1d9064201e73)

But now, I've hit another snag with this error: 
![image](https://github.com/honeynet/honeyscanner/assets/79627254/b3137908-b09f-4bc6-b60c-f68a2d163397)

The docker is running fine in the background on port 2222.

Have you seen this before, or do you have any tips on how to fix it?

**Comment by Swangeon** [comment]
Hello @ankitkat042, the issue you are running into is because the NVD API that the program reaches out to for vulnerability updates has updated the way it is interacted with. Since the update, the program as of current doesn't interact with the API in the new way

**Comment by Swangeon** [comment]
Hello @ankitkat042, the issue you are running into is because the NVD API that the program reaches out to for vulnerability information has updated the way it is interacted with. Since the update, the program as of current doesn't interact with the API in the way it needs to and there are many pull requests [here](https://github.com/honeynet/honeyscanner/pulls) (including [mine](https://github.com/honeynet/honeyscanner/pull/26)) that aim to fix the issue but none have been reviewed yet.

**Comment by aristofanischionis** [comment]
Thank you for notifying us about this issue and for creating a PR, we will try to review it ASAP and push it!

**Comment by aristofanischionis** [comment]
The problem should now be resolved, please fetch the new version of Honeyscanner and try again, I am sorry for the trouble, and thanks for being a valued member of the community and interacting with this project!
