### ISSUE TITLE
DoS attack doesn't work. Cowrie does not crash!

### ISSUE THREAD

**Issue by RudareanuLeonard** [honeynet/honeyscanner#32]

**Comment by Swangeon** [comment]
Hey @RudareanuLeonard, I want to better understand the situation, could you please provide some additional details?

**Comment by RudareanuLeonard** [comment]
> Hey @RudareanuLeonard, I want to better understand the situation, could you please provide some additional details like logs? Is the DoS attack not connecting to your Cowire docker instance?


It connects, it send packages,  but I can still connect to the honeypot after the attack end. And it shouldn't be possible... I could provide a video if needed.

**Comment by RudareanuLeonard** [comment]
Anyone? @Swangeon @adepasquale @glaslos @stricaud

**Comment by glaslos** [comment]
It would be great if you could provide the command you are running.

**Comment by aristofanischionis** [comment]
@RudareanuLeonard 
How do you run your target honeypot? What is your base OS?
I am using a MacOS host and I run cowrie from a terminal window like this:
`docker run -p 2222:2222/tcp cowrie/cowrie`
more information here [https://hub.docker.com/r/cowrie/cowrie](https://hub.docker.com/r/cowrie/cowrie).
Get the latest version of honeyscanner and try again.
If the problem persists there might be an issue with the `paramiko` library on your system. Try various fixes in order to understand where the problem is, is it on honeyscanner, or is it on the honeypot running on the docker?
Best of luck!
